### ISSUE TITLE
Trying to use the flux dev model with StableDiffusion but it doesn't work

### ISSUE THREAD

**Issue by loucoume30** [black-forest-labs/flux#163]
Hello
Any idea of what is wrong with my configuration ?

I got this error when loading the safetensor (InvalidHeaderDeserialization) : 

Loading weights [2eda627c8a] from C:\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion\flux_dev.safetensors
changing setting sd_model_checkpoint to flux_dev.safetensors: SafetensorError
Traceback (most recent call last):
  File "C:\StableDiffusion\stable-diffusion-webui\modules\options.py", line 140, in set
    option.onchange()
  File "C:\StableDiffusion\stable-diffusion-webui\modules\call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\modules\initialize_util.py", line 170, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: sd_models.reload_model_weights()), call=False)
  File "C:\StableDiffusion\stable-diffusion-webui\modules\sd_models.py", line 741, in reload_model_weights
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "C:\StableDiffusion\stable-diffusion-webui\modules\sd_models.py", line 315, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "C:\StableDiffusion\stable-diffusion-webui\modules\sd_models.py", line 291, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization

**Comment by alphanlp** [comment]
save issue! anyway to slove it?

**Comment by geronimi73** [comment]
SD-webui does not support FLUX, see https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/16314
