### ISSUE TITLE
Not running on apple silicon due to float64 tensor

### ISSUE THREAD

**Issue by Xuzzo** [black-forest-labs/flux#30]
Hello and thanks for your work.

The `scale` tensor in math.rope blocks the models from running on apple gpu.
Just changing the type to float32 seems to work.

**Comment by toddllm** [comment]
```
git diff                                         
diff --git a/src/flux/math.py b/src/flux/math.py
index 0156bb6..8c50c47 100644
--- a/src/flux/math.py
+++ b/src/flux/math.py
@@ -14,7 +14,7 @@ def attention(q: Tensor, k: Tensor, v: Tensor, pe: Tensor) -> Tensor:
 
 def rope(pos: Tensor, dim: int, theta: int) -> Tensor:
     assert dim % 2 == 0
-    scale = torch.arange(0, dim, 2, dtype=torch.float64, device=pos.device) / dim
+    scale = torch.arange(0, dim, 2, dtype=torch.float32, device=pos.device) / dim
     omega = 1.0 / (theta**scale)
     out = torch.einsum("...n,d->...nd", pos, omega)
     out = torch.stack([torch.cos(out), -torch.sin(out), torch.sin(out), torch.cos(out)], dim=-1)
   ```
   
   But, I get:
   
   ```
   python -m flux --name flux-schnell -d mps --loop 
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/flux/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Caskroom/miniconda/base/envs/flux/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tdeshane/development/llm-experiments/flux/src/flux/__main__.py", line 1, in <module>
    from .cli import app
  File "/Users/tdeshane/development/llm-experiments/flux/src/flux/cli.py", line 7, in <module>
    import torch
  File "/Users/tdeshane/development/llm-experiments/flux/.venv/lib/python3.10/site-packages/torch/__init__.py", line 13, in <module>
    import math
  File "/Users/tdeshane/development/llm-experiments/flux/src/flux/math.py", line 3, in <module>
    from torch import Tensor
ImportError: cannot import name 'Tensor' from partially initialized module 'torch' (most likely due to a circular import) (/Users/tdeshane/development/llm-experiments/flux/.venv/lib/python3.10/site-packages/torch/__init__.py)
```

What is the change needed? @Xuzzo

**Comment by Xuzzo** [comment]
The change you did is correct, but it looks like you have another issue. This import error could be happening because you have multiple versions of torch installed.  Try rebuilding your env from scratch.

**Comment by toddllm** [comment]
> The change you did is correct, but it looks like you have another issue. This import error could be happening because you have multiple versions of torch installed. Try rebuilding your env from scratch.

Built from scratch, but now:

```python -m flux --name flux-schnell -d mps --loop 
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Init model
Loading checkpoint
Init AE
Next prompt (write /h for help, /q to quit and leave empty to repeat):
"a cat"
Generating with seed 1878214292047864222:
"a cat"
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/flux/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Caskroom/miniconda/base/envs/flux/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/tdeshane/flux/src/flux/__main__.py", line 4, in <module>
    app()
  File "/Users/tdeshane/flux/src/flux/cli.py", line 250, in app
    Fire(main)
  File "/Users/tdeshane/flux/.venv/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/tdeshane/flux/.venv/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/tdeshane/flux/.venv/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/tdeshane/flux/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/Users/tdeshane/flux/src/flux/cli.py", line 216, in main
    with torch.autocast(device_type=torch_device.type, dtype=torch.bfloat16):
  File "/Users/tdeshane/flux/.venv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 238, in __init__
    raise RuntimeError(
RuntimeError: User specified an unsupported autocast device_type 'mps'
```

I am still new to this MPS stuff, so maybe I am doing something else wrong.

**Comment by Xuzzo** [comment]
There is another issue related to this #19. This error comes from torch.autocast not recognizing mps (more info about this can be found in [this long standing pytorch issue](https://github.com/pytorch/pytorch/issues/88415). In this repo, I got around it by simply removing torch.autocast in flux.cli. 

With all these hacks I was able to get the model running on my Mac. However, the generated images are really not good, so there is a bit more debugging to do...

**Comment by bghira** [comment]
it's just the positional embeds. they need fp64 precision. and it takes 40 seconds to run 4 steps on m3 max

![image](https://github.com/user-attachments/assets/78ce1945-7de6-496b-a0ba-c34d95e3e79a)

**Comment by Xuzzo** [comment]
The output of math.rope is converted to float32 anyway, so the embeddings should run on lower precision

**Comment by Ucodia** [comment]
Same result here, I tried to make it work for hours but it only gives terrible output on macOS with a M1 Max and 64GB, I see no errors in my generation output.

Any plans to make Flux compatible with capable GPUs?

![ComfyUI_02587_](https://github.com/user-attachments/assets/f0634732-ba76-4b60-a5a6-59244e2ae952)

**Comment by Xuzzo** [comment]
Refer to [this repository](https://github.com/filipstrand/mflux) for a stable implementation on Apple silicon

**Comment by hvaara** [comment]
The noise in the output image is due to a separate bug in PyTorch when using MPS. Follow https://github.com/pytorch/pytorch/issues/133520 for updates on that issue.

**Comment by Ucodia** [comment]
Thanks a ton @hvaara, this works as expected after updating to PyTorch to previous version
```
conda install pytorch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 -c pytorch
```

![ComfyUI_02602_](https://github.com/user-attachments/assets/90423ead-abe4-4905-b61d-79c87b27415f)

**Comment by hvaara** [comment]
FYI, PyTorch `v2.4.1` has been released which contains a fix for this issue, so updating to that version is also an alternative now.

**Comment by bghira** [comment]
2.5 nightly has mps fast path for attention too
